# Paper metadata
paper:
  name: "documentation"
  title: "Ant Stack Documentation and PDF Rendering Guide"
  subtitle: "Comprehensive framework for scientific publications in embodied AI"
  author: "Daniel Ari Friedman"
  email: "daniel@activeinference.institute"
  orcid: "0000-0001-6232-9096"
  output_filename: "1_ant_stack_documentation.pdf"

# Content organization
content:
  files:
    - "README.md"
    - "PDF_RENDERING_GUIDE.md"

# Asset management
assets:
  figures_dir: "assets/figures"
  mermaid_dir: "assets/mermaid"
  tmp_dir: "assets/tmp_images"
  data_dir: "assets/data"

# Build configuration
build:
  has_generated_content: false
  has_computational_analysis: false
  mermaid_preprocessing: false
  cross_reference_validation: true

# LaTeX/Pandoc settings
latex:
  document_class: "article"
  geometry: "margin=2.5cm"
  mainfont: "Latin Modern Roman"
  mathfont: "Latin Modern Math"
  bibliography: ""

# Quality assurance
validation:
  check_cross_references: true
  check_figure_captions: true
  check_unicode_symbols: true
  require_descriptive_links: true
  validate_analysis_outputs: false
